### ISSUE TITLE
Bug .... if my knowledge is good

### ISSUE THREAD

**Issue by Cs4pi** [iwoplaza/MoBends#112] opened 2020-06-25 23:20 UTC
**Describe the bug**

**Expected behavior**
The Vics Modern Warfare armors are ... how shod i call...... they have an interesting look T-T

**Screenshots**
![2020-06-26_01 13 01](https://user-images.githubusercontent.com/66576660/85804759-baf06100-b74a-11ea-9499-280c363d9dc5.png)
The Uper one is whith the mod on and the downer one without the mod
![2020-06-26_01 14 57](https://user-images.githubusercontent.com/66576660/85804760-bb88f780-b74a-11ea-835b-815932c5295b.png)

**Context (please complete the following information):**
 - Minecraft version: [1.12.2]
 - Mo' Bends version [1.0.0-beta 20.06.20]
 - Other installed mods [
![image](https://user-images.githubusercontent.com/66576660/85804676-7f559700-b74a-11ea-8062-99a12dedafc8.png) (This modlist now without the mob end mod)
]

**Comment by iwoplaza** [comment] 2021-08-05 22:19
Duplicate of #201. Let's keep the discussion to a single thread 😄.

**Closed as completed by iwoplaza** 2021-08-05 22:19 UTC
Labels: bug
