### ISSUE TITLE
Doesn't work well with "Modern Warfare"

### ISSUE THREAD

**Issue by maikon12** [iwoplaza/MoBends#71] opened 2019-07-28 04:46 UTC
O player n faz a animação de mira a  arma

**Comment by YTFrost** [comment] 2020-08-25 13:05
Vic's Modern Warfare generally doesn't work well with other mods

**Comment by iwoplaza** [comment] 2021-08-05 22:19
Duplicate of #201. Let's keep the discussion to a single thread 😄.

**Closed as completed by iwoplaza** 2021-08-05 22:19 UTC
Labels: compatibility-issue
