### ISSUE TITLE
Facial Expresions

### ISSUE THREAD

**Issue by FC67-gameandmods** [iwoplaza/MoBends#160] opened 2020-11-15 10:46 UTC
Can u add facial expresions?

**Comment by partyp770** [comment] 2021-08-10 02:08
That's beyond the scope of this mod. 

It's an interesting idea, though. If we're talking about something like your skin changing whenever you get hit, like your character's face wincing, that would be cool.

**Comment by iwoplaza** [comment] 2021-08-13 16:05
Thanks for the suggestion! Duplicate of #78, let's continue the discussion there.

**Closed as completed by iwoplaza** 2021-08-13 16:05 UTC
